name: 'Test Linux'
description: 'Tests yapscan for linux'
env:
    coverpkg: "github.com/fkie-cad/yapscan/..."
runs:
    using: "composite"
    steps:
        - name: Running unit tests
          run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg="$coverpkg" -v $(go list ./... | grep -v /acceptanceTests)
        - name: Running acceptance tests
          run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg="$coverpkg" -v -quickchecks=${QUICKCHECKS:-100} -short .
          working-directory: acceptanceTests
        - name: Consolidating coverage
          run: cat acceptanceTests/coverage.txt | tail -n+2 >> coverage.txt && rm acceptanceTests/coverage.txt
        - name: Upload coverage
          uses: actions/upload-artifact@v2
          with:
              name: coverage-linux
              path: coverage.txt
