name: Main

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop

jobs:
    build:
        runs-on: ubuntu-18.04
        strategy:
            matrix:
                go-version:
                    - 1.16
                    - 1.15
                yara-version:
                    - v4.1.1
                openssl-version:
                    - OpenSSL_1_1_1-stable
        steps:
        - uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
              go-version: ${{ matrix.go-version }}

        - name: Docker Login
          uses: docker/login-action@v1.10.0
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build libyara
          uses: ./.github/actions/build-yara
          with:
              yara-version: ${{ matrix.yara-version }}

        - name: Build for linux
          uses: ./.github/actions/build-linux

        - name: Gather linux deps
          uses: ./.github/actions/gather-linux-deps

        - name: Test on linux
          uses: ./.github/actions/test-linux

        - name: Codecov
          uses: codecov/codecov-action@v1.5.2

        - name: Crossbuild for windows
          uses: ./.github/actions/crossbuild-windows
          with:
              openssl-version: ${{ matrix.openssl-version }}
              yara-version: ${{ matrix.yara-version }}
